groups:

  - name: turrets
    frame: torso_lift_link
    spheres: t0 t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11
  - name: base
    frame: base_link
    spheres: b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13 b14 b15 b16 b17 b18 b19 b20 b21 b22 b23 b24 b25 b26 b27 b28 b29 b30 b31 b32 b33 b34 b35 b36 b37 b38 b39 b40 b41 b42 b43 b44 b45 b46
  - name: torso_upper
    frame: torso_lift_link
    spheres: s1 s2 s3 s4 s18 s19
  - name: torso_lower
    frame: base_link
    spheres: s13 s14 s15 s16 s17
  - name: tilt_laser
    frame: torso_lift_link
    spheres: s7 s8 s11 s12
  - name: head
    frame: head_pan_link
    spheres: s9 s10
  - name: right_gripper
    frame: r_wrist_roll_link
    spheres: g0 g1 g2
  - name: left_gripper
    frame: l_wrist_roll_link
    spheres: g0 g1 g2
  - name: right_forearm
    frame: r_elbow_flex_link
    spheres: fa0 fa1
  - name: left_forearm
    frame: l_elbow_flex_link
    spheres: fa0 fa1

# Base - Rear
b1: {x: -0.26, y: -0.25, z: 0.2, radius: 0.1, priority: 1}
b2: {x: -0.26, y: -0.15, z: 0.2, radius: 0.1, priority: 1}
b3: {x: -0.26, y: 0.0, z: 0.2, radius: 0.1, priority: 1}
b4: {x: -0.26, y: 0.15, z: 0.2, radius: 0.1, priority: 1}
b5: {x: -0.26, y: 0.25, z: 0.2, radius: 0.1, priority: 1}
b15: {x: -0.26, y: -0.25, z: 0.1, radius: 0.1, priority: 1}
b16: {x: -0.26, y: -0.15, z: 0.1, radius: 0.1, priority: 1}
b17: {x: -0.26, y: -0.05, z: 0.1, radius: 0.1, priority: 1}
b25: {x: -0.26, y: 0.05, z: 0.1, radius: 0.1, priority: 1}
b18: {x: -0.26, y: 0.15, z: 0.1, radius: 0.1, priority: 1}
b19: {x: -0.26, y: 0.25, z: 0.1, radius: 0.1, priority: 1}

# Base - Front
b6:  {x: 0.26, y: -0.25, z: 0.2, radius: 0.1, priority: 4}
b7:  {x: 0.26, y: -0.15, z: 0.2, radius: 0.1, priority: 3}
b8:  {x: 0.26, y: 0.000, z: 0.2, radius: 0.1, priority: 1}
b9:  {x: 0.26, y: 0.150, z: 0.2, radius: 0.1, priority: 3}
b10: {x: 0.26, y: 0.250, z: 0.2, radius: 0.1, priority: 3}
b20:  {x: 0.26, y: -0.25, z: 0.1, radius: 0.1, priority: 4}
b21:  {x: 0.26, y: -0.15, z: 0.1, radius: 0.1, priority: 3}
b22:  {x: 0.26, y: -0.05, z: 0.1, radius: 0.1, priority: 1}
b26:  {x: 0.26, y: 0.050, z: 0.1, radius: 0.1, priority: 1}
b23:  {x: 0.26, y: 0.150, z: 0.1, radius: 0.1, priority: 3}
b24:  {x: 0.26, y: 0.250, z: 0.1, radius: 0.1, priority: 3}

# Base - Laser
b12: {x: 0.26, y: 0.0, z: 0.25, radius: 0.1, priority: 1}

# Base - Right Side
b27: {x: 0.16, y: -0.25, z: 0.2, radius: 0.1, priority: 1}
b28: {x: 0.06, y: -0.25, z: 0.2, radius: 0.1, priority: 1}
b29: {x: -0.06, y: -0.25, z: 0.2, radius: 0.1, priority: 1}
b30: {x: -0.16, y: -0.25, z: 0.2, radius: 0.1, priority: 1}
b31: {x: 0.16, y: -0.25, z: 0.1, radius: 0.1, priority: 1}
b32: {x: 0.06, y: -0.25, z: 0.1, radius: 0.1, priority: 1}
b33: {x: -0.06, y: -0.25, z: 0.1, radius: 0.1, priority: 1}
b34: {x: -0.16, y: -0.25, z: 0.1, radius: 0.1, priority: 1}

# Base - Left Side
b35: {x: 0.16, y: 0.25, z: 0.2, radius: 0.1, priority: 1}
b36: {x: 0.06, y: 0.25, z: 0.2, radius: 0.1, priority: 1}
b37: {x: -0.06, y: 0.25, z: 0.2, radius: 0.1, priority: 1}
b38: {x: -0.16, y: 0.25, z: 0.2, radius: 0.1, priority: 1}
b39: {x: 0.16, y: 0.25, z: 0.1, radius: 0.1, priority: 1}
b40: {x: 0.06, y: 0.25, z: 0.1, radius: 0.1, priority: 1}
b41: {x: -0.06, y: 0.25, z: 0.1, radius: 0.1, priority: 1}
b42: {x: -0.16, y: 0.25, z: 0.1, radius: 0.1, priority: 1}

# Base - Middle
b43: {x: 0.16, y: -0.15, z: 0.2, radius: 0.1, priority: 1}
b44: {x: 0.16, y: -0.05, z: 0.2, radius: 0.1, priority: 1}
b45: {x: 0.16, y: 0.05, z: 0.2, radius: 0.1, priority: 1}
b46: {x: 0.16, y: 0.15, z: 0.2, radius: 0.1, priority: 1}


s1: {x: -0.20, y: 0.10, z: 0.16, radius: 0.14, priority: 1}
s2: {x: -0.20, y: -0.10, z: 0.16, radius: 0.14, priority: 1}
s3: {x: -0.20, y: 0.10, z: -0.04, radius: 0.14, priority: 1}
s4: {x: -0.20, y: -0.10, z: -0.04, radius: 0.14, priority: 1}
s5: {x: 0.25, y: 0.0, z: -0.01, radius: 0.06, priority: 3}
s6: {x: 0.32, y: 0.0, z: -0.01, radius: 0.06, priority: 3}
s7: {x: 0.1, y: 0.05, z: 0.23, radius: 0.08, priority: 1}
s8: {x: 0.1, y: -0.05, z: 0.23, radius: 0.08, priority: 1}
s9: {x: 0.05, y: 0.06, z: 0.08, radius: 0.18, priority: 1}
s10: {x: 0.05, y: -0.06, z: 0.08, radius: 0.18, priority: 1}
s11: {x: 0.06, y: 0.16, z: 0.23, radius: 0.08, priority: 1}
s12: {x: 0.06, y: -0.16, z: 0.23, radius: 0.08, priority: 1}
s13: {x: -0.20, y: 0.0, z: 0.38, radius: 0.17, priority: 1}
s14: {x: -0.25, y: 0.10, z: 0.35, radius: 0.14, priority: 1}
s15: {x: -0.25, y: -0.10, z: 0.35, radius: 0.14, priority: 1}
s16: {x: -0.25, y: 0.10, z: 0.55, radius: 0.14, priority: 1}
s17: {x: -0.25, y: -0.10, z: 0.55, radius: 0.14, priority: 1}
s18: {x: -0.20, y: 0.10, z: -0.26, radius: 0.14, priority: 1}
s19: {x: -0.20, y: -0.10, z: -0.26, radius: 0.14, priority: 1}
g0: {x: 0.08, y: 0.0, z: 0.00, radius: 0.07, priority: 1}
g1: {x: 0.14, y: 0.0, z: 0.00, radius: 0.07, priority: 5}
g2: {x: 0.2, y: 0.0, z: 0.00, radius: 0.03, priority: 5}
fa0: {x: 0.2, y: 0.005, z: 0.00, radius: 0.08, priority: 1}
fa1: {x: 0.3, y: -0.005, z: 0.00, radius: 0.08, priority: 1}


# Turrets
t0: {x: -0.00, y: -0.25, z: -0.45, radius: 0.1, priority: 1}
t1: {x: -0.00, y: 0.25, z: -0.45, radius: 0.1, priority: 1}
t2: {x: -0.00, y: -0.25, z: -0.35, radius: 0.1, priority: 1}
t3: {x: -0.00, y: 0.25, z: -0.35, radius: 0.1, priority: 1}
t4: {x: -0.00, y: -0.25, z: -0.25, radius: 0.1, priority: 1}
t5: {x: -0.00, y: 0.25, z: -0.25, radius: 0.1, priority: 1}
t6: {x: -0.00, y: -0.15, z: -0.45, radius: 0.1, priority: 1}
t7: {x: -0.00, y: 0.15, z: -0.45, radius: 0.1, priority: 1}
t8: {x: -0.00, y: -0.15, z: -0.35, radius: 0.1, priority: 1}
t9: {x: -0.00, y: 0.15, z: -0.35, radius: 0.1, priority: 1}
t10: {x: -0.00, y: -0.15, z: -0.25, radius: 0.1, priority: 1}
t11: {x: -0.00, y: 0.15, z: -0.25, radius: 0.1, priority: 1}

